### ISSUE TITLE
🐛 [BUG] <Manyana撤回图片功能似乎无效>

### ISSUE THREAD

**Issue by lux-QAQ** [avilliai/Manyana#10]
# 撤回功能无效
### 本来是在~~找涩图~~测试Manyana各个指令是否正常时，发现群消息出现_违禁词_和_违规图_时，撤回信息无效。
<p>测试时提示我_权限不够_，但是我使bot成为管理员和群主后，并且检查自己不是管理员或者群主后，再次测试，问题仍然出现。</p>

![1](https://github.com/avilliai/Manyana/assets/51485740/50f8b5fd-d258-46bd-b3ee-5d3141dd0c51)
![2](https://github.com/avilliai/Manyana/assets/51485740/9085f05d-372a-4309-bd9c-f192daa086c1)

```
2024-05-10 22:55:53,318 - Manayana - INFO - 检查arona订阅更新
2024-05-10 22:55:53,326 - Manayana - INFO - 检查国服未来视更新
2024-05-10 22:56:18,494 - Manayana - INFO - 检查国服活动更新
2024-05-10 22:56:20,018 - Manayana - INFO - 更新数据
2024-05-10 22:56:21,366 - Manayana - INFO - 获取到违禁词列表['涩图']
Traceback (most recent call last):
  File "/home/mc/miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/utils.py", line 20, in async_with_exception
    return await async_(obj)
  File "/home/mc/miniconda3/envs/qqbot/lib/python3.9/site-packages/mirai/utils.py", line 14, in async_
    return (await obj) if inspect.isawaitable(obj) else obj
  File "/home/mc/napcatqq/Manyana/run/wReply.py", line 407, in mohu
    keys1 = superDict.get("publicLexicon").keys()
AttributeError: 'NoneType' object has no attribute 'keys'
2024-05-10 22:56:21,469 - Manayana - ERROR - 关键词撤回失败！
2024-05-10 22:56:21,572 - Manayana - ERROR - 禁言失败，权限可能过低
2024-05-10 22:56:39,769 - Manayana - INFO - 开始更新数据
2024-05-10 22:56:39,868 - Manayana - INFO - 已读取信任用户0个
2024-05-10 22:56:43,611 - Manayana - INFO - 检查国际服总力更新
```

<p>我不知道这会不会是 llonebot 或者 overflow的问题</p>
<p>
环境和版本信息：
OS：linux
虚拟环境：conda
python ：3.9.0
Manyana是从github直接git clone下来的版本
Manyana启动器版本为V2
正在运行 MiraiConsole v2.16.0, 构建于 2023-10-20 06:28:10.
正在运行 Overflow v2.16.0-febc5da-SNAPSHOT, 构建于 2024-04-01 12:16:30.
Frontend Terminal: version 2.16.0, provided by Mamoe Technologies
启动时间: 2024-05-10 19:36:32, 已运行 4时 0分.

权限服务: 内置权限服务
Onebot 实现信息: 
  - 2395046328: LLOneBot v3.24.2.

插件列表 (7): MiraiBlackList v1.1.2, mirai-api-http v2.9.1, 点歌插件 v1.2.0, PetPet v5.0, Chat Command v0.6.0, Silk Converter v0.0.6-fix-cssxsh, PatPat v2.0.1

已挂起待回收对象数: 0
  　　　　　　 已提交  |  初始  |  已使用  |   最大  
   　堆内存: 302.0MB | 62.0MB | 75.87MB | 976.0MB
   非堆内存: 82.31MB | 7.31MB | 79.33MB |   -1   

</p>

**Comment by avilliai** [comment]
自去年qq某次更新后，撤回功能失效，目前暂无解决方案。

**Comment by avilliai** [comment]
至于另一个报错，检查原本自带的data/autoReply/lexicon/publicLexicon.xlsx，当该文件丢失或者内容格式异常无法正常读取将出现该报错。
词库部分(wReply.py)源码直接从22年的另一个项目移植，问题很多，等日后大改。

**Comment by lux-QAQ** [comment]
禁言好像也寄了:loudly_crying_face:

**Comment by avilliai** [comment]
![Screenshot_2024_0510_235506](https://github.com/avilliai/Manyana/assets/99066610/cb40c270-fdf0-4010-92b4-1296fd479488)
